const Discord = require('discord.js');

exports.run = async(client, msg) => {


    const embed = new Discord.MessageEmbed()
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @here')
    .addField(`! Anıl Was Here ?!💀`, 'BiaT Et?! @everyone')
    
    


    
    
    .setColor('RED')
  .setFooter('! Anıl Server Nuker')
    .setTimestamp()
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)
msg.channel.send(embed)


}; 

module.exports.conf = {
aliases: ['spam','s','spm'],
permLevel: 0, 
kategori: 'spam'
};

module.exports.help = {
    name: 'spam',
    description: 'spam atar',
    usage: 'spam'
};